### ISSUE TITLE
exchangesStack : delete : options : supprimer deux options  

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpNumerique2018#15]
Supprimer stepPlot et drawPoints 

@payementcha tu valides qu'on ne veut pas stepPlot pour les lignes ? 

cf. image ci-dessous 

avec l'option 

![exchangesstack2](https://user-images.githubusercontent.com/22026724/35334765-b056db7e-0113-11e8-96dc-55c369685860.png)

sans l'option 

![exchangesstack1](https://user-images.githubusercontent.com/22026724/35334772-b531f71e-0113-11e8-877d-e557bae6fb26.png)

**Comment by payementcha** [comment]
Finalement pour les échanges, le stepPlot est meilleur que les lignes.
Laisser les deux options.

**Comment by jalazawa** [comment]
Ok, on garde ces deux options.
