### ISSUE TITLE
Un onglet à propos 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/bpNumerique2018#43]
@payementcha est-ce que tu peux confirmer ce besoin ? 

Avec un lien vers le site openData RTE ? 

Un lien vers les pdf du BP 2017 à télécharger ? 

Un autre lien ?

**Comment by payementcha** [comment]
Dans l'idée où on veut limiter l'application à de la visualisation, pas besoin de cet onglet finalement.
Les liens seront sur le site institutionnel.
