### ISSUE TITLE
plotMap : Séparer les noeuds NI et GB sur la carte

### ISSUE THREAD

**Issue by payementcha** [rte-antares-rpackage/bpNumerique2018#44]
Est-ce qu'il est possible de séparer l'Irlande du Nord de la Grande-Bretagne ?

**Comment by jalazawa** [comment]
OUI 

Sur le tab Layout builder rajouter 'united Kingdom' à l'argument states. 

Appuyer sur Set map

![layout1](https://user-images.githubusercontent.com/22026724/35376660-55126bf4-01ac-11e8-9548-49a610eb7b73.png)

Voilà le résultat 

![layout0](https://user-images.githubusercontent.com/22026724/35376776-db48d17c-01ac-11e8-974f-93d00db4337b.png)


Une fois les points bien placés appuyer sur Done 

Voilà le résultat 

![layout2](https://user-images.githubusercontent.com/22026724/35376688-77c10de0-01ac-11e8-92c0-39a1dd5c27d0.png)


Refaire les étapes 1 et 2 si besoin afin d'avoir la carte voulue 

![layout3](https://user-images.githubusercontent.com/22026724/35376823-09242c22-01ad-11e8-97cf-07f6952dd5af.png)


Pour info, on fusionne les régions administratives les plus proches des points. 

La solution n'est pas parfaite. 

@payementcha ça te vas ?

**Comment by payementcha** [comment]
OK je vais travailler là-dessus pour faire un jolie layout, je pense que ça ira.

**Comment by jalazawa** [comment]
OK, je clos la demande pour l'instant.

**Comment by bthieurmel** [comment]
@payementcha : je pourrais le faire, mais une fois que l'on aura les bonnes données .h5
